/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiRepositoryUrlsResponse
 */
export interface ApiRepositoryUrlsResponse {
    /**
     * URLs of the repositories
     * @type {Array<string>}
     * @memberof ApiRepositoryUrlsResponse
     */
    urls?: Array<string>;
}

/**
 * Check if a given object implements the ApiRepositoryUrlsResponse interface.
 */
export function instanceOfApiRepositoryUrlsResponse(value: object): value is ApiRepositoryUrlsResponse {
    return true;
}

export function ApiRepositoryUrlsResponseFromJSON(json: any): ApiRepositoryUrlsResponse {
    return ApiRepositoryUrlsResponseFromJSONTyped(json, false);
}

export function ApiRepositoryUrlsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRepositoryUrlsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'urls': json['urls'] == null ? undefined : json['urls'],
    };
}

export function ApiRepositoryUrlsResponseToJSON(json: any): ApiRepositoryUrlsResponse {
    return ApiRepositoryUrlsResponseToJSONTyped(json, false);
}

export function ApiRepositoryUrlsResponseToJSONTyped(value?: ApiRepositoryUrlsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'urls': value['urls'],
    };
}
